/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCarousel {
        "autoplay": boolean;
        "autoplayDelay": number;
        "change": (index: number) => Promise<void>;
        "hideArrows": boolean;
        "hideDots": boolean;
        "next": () => Promise<void>;
        "previous": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface MyCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyCarouselElement;
}
declare global {
    interface HTMLMyCarouselElement extends Components.MyCarousel, HTMLStencilElement {
    }
    var HTMLMyCarouselElement: {
        prototype: HTMLMyCarouselElement;
        new (): HTMLMyCarouselElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-carousel": HTMLMyCarouselElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyCarousel {
        "autoplay"?: boolean;
        "autoplayDelay"?: number;
        "hideArrows"?: boolean;
        "hideDots"?: boolean;
        "onChange-slide"?: (event: MyCarouselCustomEvent<number>) => void;
        "onNext-slide"?: (event: MyCarouselCustomEvent<void>) => void;
        "onPrevious-slide"?: (event: MyCarouselCustomEvent<void>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-carousel": MyCarousel;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-carousel": LocalJSX.MyCarousel & JSXBase.HTMLAttributes<HTMLMyCarouselElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
